name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t hellnah71/email-app ./email-app \
          --build-arg VITE_REACT_APP_API_URL=${{ secrets.API_URL }}
      - name: Publish image to docker hub
        run: docker push hellnah71/email-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -l ubuntu  ec2-54-204-113-27.compute-1.amazonaws.com <<EOF
          docker pull hellnah71/email-app:latest
          docker rm -f frontendContainer
          docker run -d -p 80:80 --name frontendContainer hellnah71/email-app:latest
          docker container prune -f
          docker image prune -a -f
          EOF
