name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t hellnah71/email-app ./email-app \
          --build-arg VITE_REACT_APP_API_URL=${{ secrets.API_URL }}
      - name: Publish image to docker hub
        run: docker push hellnah71/email-app:latest

  deploy:
    needs: build
    runs-on: ip-172-31-16-10
    steps:
      - name: Pull image from docker hub
        run: docker pull hellnah71/email-app:latest
      - name: Delete Old Container
        run: docker rm -f frontendContainer
      - name: Run docker container
        run: docker run -d -p 80:80 --name frontendContainer hellnah71/email-app:latest
